### PR TITLE
Adding Dockerfile

### PR DESCRIPTION
**Pull request by m0sa**
Adds a Dockerfile.

For testing the PR you can call:
```bash
docker build https://github.com/m0sa/wheelofblame.git
```

The idea is to allows easy building / running of the image, directly from github (without checking out code or relying on hub.docker.com), via:

```bash
docker build https://github.com/balpha/wheelofblame.git -t wheelofblame
docker run -e WOB_TOKEN=... WOB_APP_TOKEN=... WOB_SIGNING_SECRET=... wheelofblame
```

### CODE REVIEW

**Comment by balpha** [comment]
Oh hello there Samo, I guess you're missing your favorite coworker -- ***the wheel*** 😁

Looks good, will give it a spin tomorrow. Would you mind adding a sentence or two to the readme as well?

**Comment by m0sa** [comment]
Not my fault

**Review by balpha — APPROVED** [review]
Works like a charm! The `docker run` command needs a `-e` for each individual env var, but I can fix that in a follow-up

**Comment by balpha** [comment]
Done in eecd6f5f74dd857190eb5c6c139f77c752d59c69. Thanks for the PR!

**Pull request merged**
